"use client";

import { ChakraProvider, Box } from "@chakra-ui/react";
import Link from "next/link";
import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub,
        AiFillLinkedin, 
        AiFillYoutube,
        AiFillMail} from 'react-icons/ai';
import Image from "next/image";
import headshot from '/public/headshot-transparent.png';
import yale from '/public/yale-logo.png';
import cfa from '/public/cfa-logo.png';
import deepmedia from '/public/deepmedia-logo.png';
import shutter from '/public/shutter.png';
import nyctravel from '/public/nyctravel.png';
import tictactoe from '/public/tictactoe.png';
import politic from '/public/politic.png';
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <ChakraProvider>

      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Alex Shin Portfolio</title>
          <meta name = "description" content = "generated by create next app"></meta>
          <link rel = "icon" href="/favicon.ico"/>
        </Head>

        <main className = "bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
          <section className="min-h-screen"> 
            <nav className = "py-10 mb-12 flex justify-between">
              <h1 className = "text-xl font-sans dark:text-slate-300">Alex Shin</h1>
              <ul className="flex items.center">
                <li className="dark:text-white"><BsFillMoonStarsFill onClick = {() => setDarkMode(!darkMode)}className = "cursor-pointer text-2xl"/></li>
                <li>
                  <a href = "public/Alex Shin Resume 2023.pdf" target="_blank" className="bg-gradient-to-br from-blue-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8">
                    Resume
                  </a>
                </li>

              </ul>
            </nav>
            <div className = "text-center p-10">
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Alex Shin</h2>
              <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Developer and Engineer</h3>
              <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-2xl mx-auto dark:text-slate-400">
                Currently a <span className="text-teal-500">third-year</span> undergraduate pursuing an Bachelor of Science at <span className="text-teal-500">Yale College</span> majoring in <span className="text-teal-500">Electrical Engineering</span> and <span className="text-teal-500">Computer Science</span>. 
                Join me down below and let's get started!
              </p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <Link href = "https://www.linkedin.com/in/alexjshin/" target="_blank">
                <AiFillLinkedin className="dark:text-white"/>
              </Link>
              <Link href = "mailto:alex.shin@yale.edu" target="_blank">
                <AiFillMail className="dark:text-white"/>
              </Link>
              <Link href = "https://www.youtube.com/@alexshin1202" target="_blank">
                <AiFillYoutube className="dark:text-white"/>
              </Link>
              <Link href = "https://github.com/alexjshin" target="_blank">
                <AiFillGithub className="dark:text-white" />
              </Link>
            </div>
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 m-10 overflow-hidden md:h-96 md:w-96">
              <Image src = {headshot} layout = "fill" objectFit="cover"/>
            </div>
          </section>
          
          <section>
            <div className="mx-auto">
              <h3 className="text-3xl py-1 mx-auto dark:text-white">Education/Experience</h3>
              <p className="text-md py-2 leading-8 text-gray-800 mx-auto dark:text-slate-400">
                My journey as a software engineer, developer, and student.
              </p>
            </div>
            <div className="lg:flex lg:justify-items-stretch gap-10 max-w-screen-lg mx-auto">
              <div className=" text-center shadow-lg p-10 rounded-xl my-10 mx-auto bg-gradient-to-b from-indigo-500 to-white dark:bg-gradient-to-b dark:from-blue-300 dark:to-teal-500">
                <Image src={yale} width = {250} height = {250} className="mx-auto"/>
                <h2 className="text-black text-xl font-bold py-8 pb-2">Class of 2025</h2>
                <span className="font-semibold underline">Major</span>
                <p className="text-black py-1"> Electrical Engineering and Computer Science</p>
                <span className="font-semibold underline">Activities</span>
                <p className="text-black py-1">Yale Club Water Polo, Engineers without Borders, Yale Politic (Tech Team), Yale Computer Society, Yale
Entrepreneurial Society</p>
              </div>
              <div className="lg:min-w-[13rem] text-center shadow-lg p-10 rounded-xl my-10 mx-auto bg-gradient-to-b from-indigo-500 to-slate-300 dark:bg-gradient-to-b dark:from-blue-300 dark:to-teal-500">
                <Image src={deepmedia} width = {175} height = {175} className="mx-auto"/>
                <h2 className="text-black text-xl font-bold py-8 pb-2">Software Engineering/Product Development Intern</h2>
                <p className="text-black py-1 font-semibold">June 2022 - December 2022</p>
                <span className="font-semibold underline">Skills Used</span>
                <p className="text-black py-1">React.js, Node.js, AWS, Python</p>
                <span className="font-semibold underline">Primary Projects</span>
                <div className="text-black py-1">
                  <ul>
                    <li>Overviewed English-Korean auto translations.</li>
                    <li>Implemented waveform generator in python for audio files for Dubsync as well as general frontend organization and design.</li>
                  </ul>
                </div>
              </div>
              <div className=" text-center shadow-lg p-10 pt-7 rounded-xl my-10 mx-auto bg-gradient-to-b from-indigo-500 to-white dark:bg-gradient-to-b dark:from-blue-300 dark:to-teal-500">
                <Image src={cfa} width = {230} height = {230} className="mx-auto"/>
                <h2 className="text-black text-xl font-bold py-8 pb-2">Software Engineering Intern</h2>
                <p className="text-black py-1 font-semibold">May 2023 - August 2023</p>
                <span className="font-semibold underline">Skills Used</span>
                <p className="text-black py-1">Python, AWS, Docker/Kubernetes, Flask, DynamoDB, React.js, Backstage</p>
                <span className="font-semibold underline">Primary Projects</span>
                <p className="text-black py-1">Utilized Docker containerization to deploy full-stack API server in Kubernetes, using React.js frontend, Flask backend, DynamoDB database, and webhooks.</p>
              </div>
            </div>
          </section>
          <section>
            <div>
              <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-slate-400">
                Since the beginning of m y journey as a feelance developer, 
                I've done remote work for
              </p>
            </div>
            <div className="pb-20 flex flex-col gap-10 lg:flex-row lg:flex-wrap">
              <div className="rounded-lg shadow-xl dark:shadow-slate-400 bg-slate-400 basis-1/3 flex-1" >
                <div className=" rounded-lg object-cover " width={'100%'} height={'100%'} layout = "responsive">
                  <h1 className="p-5 font-bold text-lg underline text-black text-center">Shutter Visualizations</h1>
                  <Image src = {shutter} className = "rounded-3xl pb-2 w-3/4 h-3/4 m-auto"></Image>
                  <p className="px-10 pb-1 text-sm text-center">Created interactive visualizations using data collected by Shutter, 
                    a robot photographer from the Yale Interactive Machines Group. Used Plotly, MatPlotLib, Numpy, and Scipy
                    python packages in Juypter Notebook. Used React.js and Chakra Ui to host these visualizations on a fully-frontend
                    interactive website. Aided in research and analysis of shutter data of ~100 different social interactions.
                  </p>
                </div>
                <div className="flex gap-10 pb-5 mt-10">
                  <Link className="mx-auto hover:underline hover:text-blue-600" target="_blank" href = "https://github.com/alexjshin/shutter_web">View in Github</Link>
                  <Link className="mx-auto hover:underline hover:text-blue-600" target="_blank" href = "https://main--ornate-sundae-b6f214.netlify.app/">View Website</Link>
                </div>
              </div>
              <div className="rounded-lg shadow-xl dark:shadow-slate-400 bg-slate-400 basis-1/3 flex-1" >
                <div className="mb-15 rounded-lg object-cover " width={'100%'} height={'100%'} layout = "responsive">
                  <h1 className="p-5 font-bold text-lg underline text-black text-center">TicTacToe Game</h1>
                  <Image src = {tictactoe} className = "rounded-3xl mb-2 pb-3 w-3/4 h-3/4 m-auto"></Image>
                  <p className="px-10 pb-1 text-sm text-center">
                    Very special project to me as it this was one of my very first web apps I made. Fully-frontend webapp built using React.js. Responsive on mobile devices as well.
                  </p>
                </div>
                <div className="flex gap-10 pb-5 pt-20 mt-12">
                  <Link className="mx-auto hover:underline hover:text-blue-600" target="_blank" href = "https://github.com/alexjshin/tictactoe">View in Github</Link>
                  <Link className="mx-auto hover:underline hover:text-blue-600" target="_blank" href = "https://bit.ly/alexjshintictactoe">View Website</Link>
                </div>
              </div>
              <div className="rounded-lg shadow-xl dark:shadow-slate-400 bg-slate-400 basis-1/3 flex-1" >
                <div className="pb-5 flex flex-col rounded-lg object-cover " width={'100%'} height={'100%'} layout = "responsive">
                  <h1 className="p-5 font-bold text-lg underline text-black text-center">New York Travel</h1>
                  <Image src = {nyctravel} className = "rounded-3xl pb-2 w-3/4 h-3/4 m-auto"></Image>
                  <p className="px-10 pb-1 text-sm text-center">
                    Developed a web application for creating trip itineraries for New York using SQLite, React.js, Node.js, and Express, which provides interactive timeline features and convenient links to transportation options. Used Google Maps API.
                  </p>
                </div>
                <div className="flex gap-10 pb-5 pt-20">
                  <Link className="mx-auto hover:underline hover:text-blue-600" target="_blank" href = "https://github.com/yale-cpsc-419-sp23/project-project-group-6/tree/main/new-york-travel">View in Github</Link>
                </div>
              </div>
              <div className="rounded-lg shadow-xl dark:shadow-slate-400 bg-slate-400 basis-1/3 flex-1" >
                <div className="pb-10 flex flex-col rounded-lg object-cover " width={'100%'} height={'100%'} layout = "responsive">
                  <h1 className="p-5 font-bold text-lg underline text-black text-center">Yale Politic</h1>
                  <Image src = {politic} className = "rounded-3xl pb-2 w-3/4 h-3/4 m-auto"></Image>
                  <p className="px-10 pb-1 text-sm text-center">
                    Worked with the Tech Team for the Yale Politic newspaper for the frontend development of the Yale Politic website.
                    Designed and developed primary user interface functions: scrolling artical boxes, navigation bar, dropdown menus (+general graphic design/UI). Deployed website to over 6000+ Yale students.
                    Utilized React.js, Node.js, AWS, Python.
                  </p>
                </div>
                <div className="flex gap-10 pb-5">
                  <Link className="mx-auto hover:underline hover:text-blue-600" target="_blank" href = "https://thepolitic.org/">View Website</Link>
                </div>
              </div>
            </div>
            
          </section>
        </main>
      </div>
    </ChakraProvider>
  )
}

